### ISSUE TITLE
[bug] Windows CRLF line endings cause "Invalid frontmatter format" build error 

### ISSUE THREAD

**Issue by rochacbruno** [sebastienrousseau/frontmatter-gen#1]
Hi, I am using `frontmatter-gen` for [marmite](https://github.com/rochacbruno/marmite)

One user reported the issue https://github.com/rochacbruno/marmite/issues/99 

Which from my research is not a bug on my code, bug a general `frontmatter-gen` problem.
>  its coming from \frontmatter-gen-0.0.2\src\error.rs and \extractor.rs, because the latter searches for "---\n" when looking for data, and there is no such line ending on Windows-made files.

**Comment by sebastienrousseau** [comment]
@rochacbruno Thank you very much for this! I will release it later this evening. Good luck with Marmite and thanks for helping!
